# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_main.ui'
#
# Created: Sun May 31 15:55:33 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(495, 468)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tab_main = QtGui.QTabWidget(self.centralwidget)
        self.tab_main.setAutoFillBackground(False)
        self.tab_main.setObjectName(_fromUtf8("tab_main"))
        self.tab_settings = QtGui.QWidget()
        self.tab_settings.setObjectName(_fromUtf8("tab_settings"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_settings)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setSpacing(20)
        self.gridLayout.setContentsMargins(30, -1, 0, -1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.tab_settings)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.tab_settings)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 1, 1, 1, 1)
        self.serverSocketTypeCBox = QtGui.QComboBox(self.tab_settings)
        self.serverSocketTypeCBox.setObjectName(_fromUtf8("serverSocketTypeCBox"))
        self.serverSocketTypeCBox.addItem(_fromUtf8(""))
        self.serverSocketTypeCBox.addItem(_fromUtf8(""))
        self.serverSocketTypeCBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.serverSocketTypeCBox, 2, 2, 1, 1)
        self.serverPortTextLine = QtGui.QLineEdit(self.tab_settings)
        self.serverPortTextLine.setObjectName(_fromUtf8("serverPortTextLine"))
        self.gridLayout.addWidget(self.serverPortTextLine, 1, 2, 1, 1)
        self.serverAddressTextLine = QtGui.QLineEdit(self.tab_settings)
        self.serverAddressTextLine.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.serverAddressTextLine.setObjectName(_fromUtf8("serverAddressTextLine"))
        self.gridLayout.addWidget(self.serverAddressTextLine, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab_settings)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtGui.QLabel(self.tab_settings)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self.tab_settings)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 0, 1, 1, 1)
        self.line_4 = QtGui.QFrame(self.tab_settings)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout.addWidget(self.line_4, 2, 1, 1, 1)
        self.connectButton = QtGui.QPushButton(self.tab_settings)
        self.connectButton.setObjectName(_fromUtf8("connectButton"))
        self.gridLayout.addWidget(self.connectButton, 3, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.line = QtGui.QFrame(self.tab_settings)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.connectionStatusTextBox = QtGui.QTextEdit(self.tab_settings)
        self.connectionStatusTextBox.setObjectName(_fromUtf8("connectionStatusTextBox"))
        self.horizontalLayout.addWidget(self.connectionStatusTextBox)
        self.line_5 = QtGui.QFrame(self.tab_settings)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.horizontalLayout.addWidget(self.line_5)
        self.label_4 = QtGui.QLabel(self.tab_settings)
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setPixmap(QtGui.QPixmap(_fromUtf8("./src/arduino_image.png")))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tab_main.addTab(self.tab_settings, _fromUtf8(""))
        self.tab_plot = QtGui.QWidget()
        self.tab_plot.setObjectName(_fromUtf8("tab_plot"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_plot)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.mplplotwidget = MplPlotWidget(self.tab_plot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplplotwidget.sizePolicy().hasHeightForWidth())
        self.mplplotwidget.setSizePolicy(sizePolicy)
        self.mplplotwidget.setObjectName(_fromUtf8("mplplotwidget"))
        self.verticalLayout_4.addWidget(self.mplplotwidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.startMonitButton = QtGui.QPushButton(self.tab_plot)
        self.startMonitButton.setObjectName(_fromUtf8("startMonitButton"))
        self.horizontalLayout_2.addWidget(self.startMonitButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.tab_main.addTab(self.tab_plot, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tab_main, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 495, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_main.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.actionAbout, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.showFullScreen)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ArduinoMonitor", None))
        self.label_2.setText(_translate("MainWindow", "Port serwera:", None))
        self.serverSocketTypeCBox.setItemText(0, _translate("MainWindow", "AF_INET ", None))
        self.serverSocketTypeCBox.setItemText(1, _translate("MainWindow", "AF_UNIX ", None))
        self.serverSocketTypeCBox.setItemText(2, _translate("MainWindow", "AF_INET6 ", None))
        self.label_3.setText(_translate("MainWindow", "Typ gniazda:", None))
        self.label.setText(_translate("MainWindow", "Adres serwera:", None))
        self.connectButton.setText(_translate("MainWindow", "TEST POŁĄCZENIA", None))
        self.tab_main.setTabText(self.tab_main.indexOf(self.tab_settings), _translate("MainWindow", "Ustawienia", None))
        self.startMonitButton.setText(_translate("MainWindow", "ROZPOCZNIJ MONITORING", None))
        self.tab_main.setTabText(self.tab_main.indexOf(self.tab_plot), _translate("MainWindow", "Wykres", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionAbout.setText(_translate("MainWindow", "About...", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))

from .mplplotwidget import MplPlotWidget
